version: 2

# Build settings
sphinx:
  configuration: docs/conf.py  # Path to your Sphinx configuration file

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: docs/requirements.txt  # Path to requirements file
